apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: krawat10/api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: mssql-connection-string 
            - name: CalculationURL
              valueFrom:
                configMapKeyRef:
                  name: calculation-configmap
                  key: calculation_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort # can test app
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 31001 # how to connect using NodePort
