apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculation-deployment
  labels:
    app: calculation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculation
  template:
    metadata:
      labels:
        app: calculation
    spec:
      containers:
        - name: calculation
          image: krawat10/calculation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: mssql-connection-string 
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: calculation-service
spec:
  type: NodePort
  selector:
    app: calculation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31006


    