apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  mssql-root-password: UGFzc0B3b3Jk
  mssql-connection-string: U2VydmVyPWRiLDE0MzM7RGF0YWJhc2U9bXNzcWwtc2VydmljZTtVc2VyPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDs=