name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker shoppingapp image
      with:
        image: krawat10/api
        tags: latest
        registry: docker.io
        dockerfile: API/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker shoppingapi image
      with:
        image: krawat10/calculation
        tags: latest
        registry: docker.io
        dockerfile: Calculation/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
