on: [push]

name: example

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        namespace: simple-cloud-native
    
    - name: "Deploy application"
      uses: okteto/apply@latest
      with:
        namespace: simple-cloud-native
        manifest: okteto.yml

    - name: "Push changes"
      uses: okteto/push@latest
      with:
        namespace: simple-cloud-native
